/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50732
Source Host           : localhost:3306
Source Database       : bank_forms

Target Server Type    : MYSQL
Target Server Version : 50732
File Encoding         : 65001

Date: 2021-05-03 20:55:58
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `corporate`
-- ----------------------------
DROP TABLE IF EXISTS `corporate`;
CREATE TABLE `corporate` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `productType` varchar(10) DEFAULT NULL,
  `entityType` varchar(10) DEFAULT NULL,
  `investmentObjective` varchar(255) DEFAULT NULL,
  `businessName` varchar(255) DEFAULT NULL,
  `certificateIncorporationNumber` varchar(255) DEFAULT NULL,
  `tin` varchar(255) DEFAULT NULL,
  `dateIncorporationRegistration` varchar(255) DEFAULT NULL,
  `licenseNumber` varchar(255) DEFAULT NULL,
  `jurisdictionIncorporation` varchar(255) DEFAULT NULL,
  `parentCompanyIncorporation` varchar(255) DEFAULT NULL,
  `natureOfBusiness` varchar(255) DEFAULT NULL,
  `industry` varchar(255) DEFAULT NULL,
  `principalPlaceOfBusiness` varchar(255) DEFAULT NULL,
  `gps` varchar(255) DEFAULT NULL,
  `emailAddress` varchar(255) DEFAULT NULL,
  `websiteAddress` varchar(255) DEFAULT NULL,
  `phone1` varchar(255) DEFAULT NULL,
  `phone2` varchar(255) DEFAULT NULL,
  `sig1Title` varchar(255) DEFAULT NULL,
  `sig1Tin` varchar(255) DEFAULT NULL,
  `sig1Surname` varchar(255) DEFAULT NULL,
  `sig1Name` varchar(255) DEFAULT NULL,
  `sig1Dob` varchar(255) DEFAULT NULL,
  `sig1MaidenName` varchar(255) DEFAULT NULL,
  `sig1Pob` varchar(255) DEFAULT NULL,
  `sig1MaritalStatus` varchar(255) DEFAULT NULL,
  `sig1Spouse` varchar(255) DEFAULT NULL,
  `sig1MotherMaidenName` varchar(255) DEFAULT NULL,
  `sig1MaidenContactNumber` varchar(255) DEFAULT NULL,
  `sig1CountryOfOrigin` varchar(255) DEFAULT NULL,
  `sig1CountryOfResidence` varchar(255) DEFAULT NULL,
  `sig1ResidencePermitNumber` varchar(255) DEFAULT NULL,
  `sig1PlaceOfIssue` varchar(255) DEFAULT NULL,
  `sig1PermitIssueDate` varchar(255) DEFAULT NULL,
  `sig1PermitExpiryDate` varchar(255) DEFAULT NULL,
  `sig1IdType` varchar(255) DEFAULT NULL,
  `sig1ID` varchar(255) DEFAULT NULL,
  `sig1DateOfIssue` varchar(255) DEFAULT NULL,
  `sig1DateExpiry` varchar(255) DEFAULT NULL,
  `sig1JobTitle` varchar(255) DEFAULT NULL,
  `sig1EmailAddress` varchar(255) DEFAULT NULL,
  `sig1ResidentialAddress` varchar(255) DEFAULT NULL,
  `sig2Title` varchar(255) DEFAULT NULL,
  `sig2Tin` varchar(255) DEFAULT NULL,
  `sig2Surname` varchar(255) DEFAULT NULL,
  `sig2Name` varchar(255) DEFAULT NULL,
  `sig2Dob` varchar(255) DEFAULT NULL,
  `sig2MaidenName` varchar(255) DEFAULT NULL,
  `sig2Pob` varchar(255) DEFAULT NULL,
  `sig2MaritalStatus` varchar(255) DEFAULT NULL,
  `sig2Spouse` varchar(255) DEFAULT NULL,
  `sig2MotherMaidenName` varchar(255) DEFAULT NULL,
  `sig2MaidenContactNumber` varchar(255) DEFAULT NULL,
  `sig2CountryOfOrigin` varchar(255) DEFAULT NULL,
  `sig2CountryOfResidence` varchar(255) DEFAULT NULL,
  `sig2ResidencePermitNumber` varchar(255) DEFAULT NULL,
  `sig2PlaceOfIssue` varchar(255) DEFAULT NULL,
  `sig2PermitIssueDate` varchar(255) DEFAULT NULL,
  `sig2PermitExpiryDate` varchar(255) DEFAULT NULL,
  `sig2IdType` varchar(255) DEFAULT NULL,
  `sig2ID` varchar(255) DEFAULT NULL,
  `sig2DateOfIssue` varchar(255) DEFAULT NULL,
  `sig2DateExpiry` varchar(255) DEFAULT NULL,
  `sig2JobTitle` varchar(255) DEFAULT NULL,
  `sig2EmailAddress` varchar(255) DEFAULT NULL,
  `sig2ResidentialAddress` varchar(255) DEFAULT NULL,
  `sig3Title` varchar(255) DEFAULT NULL,
  `sig3Tin` varchar(255) DEFAULT NULL,
  `sig3Surname` varchar(255) DEFAULT NULL,
  `sig3Name` varchar(255) DEFAULT NULL,
  `sig3Dob` varchar(255) DEFAULT NULL,
  `sig3MaidenName` varchar(255) DEFAULT NULL,
  `sig3Pob` varchar(255) DEFAULT NULL,
  `sig3MaritalStatus` varchar(255) DEFAULT NULL,
  `sig3Spouse` varchar(255) DEFAULT NULL,
  `sig3MotherMaidenName` varchar(255) DEFAULT NULL,
  `sig3MaidenContactNumber` varchar(255) DEFAULT NULL,
  `sig3CountryOfOrigin` varchar(255) DEFAULT NULL,
  `sig3CountryOfResidence` varchar(255) DEFAULT NULL,
  `sig3ResidencePermitNumber` varchar(255) DEFAULT NULL,
  `sig3PlaceOfIssue` varchar(255) DEFAULT NULL,
  `sig3PermitIssueDate` varchar(255) DEFAULT NULL,
  `sig3PermitExpiryDate` varchar(255) DEFAULT NULL,
  `sig3IdType` varchar(255) DEFAULT NULL,
  `sig3ID` varchar(255) DEFAULT NULL,
  `sig3DateOfIssue` varchar(255) DEFAULT NULL,
  `sig3DateExpiry` varchar(255) DEFAULT NULL,
  `sig3JobTitle` varchar(255) DEFAULT NULL,
  `sig3EmailAddress` varchar(255) DEFAULT NULL,
  `sig3ResidentialAddress` varchar(255) DEFAULT NULL,
  `bankName` varchar(255) DEFAULT NULL,
  `accountName` varchar(255) DEFAULT NULL,
  `accountNumber` varchar(255) DEFAULT NULL,
  `bankBranch` varchar(255) DEFAULT NULL,
  `trusteeSurname2` varchar(255) DEFAULT NULL,
  `trusteeName2` varchar(255) DEFAULT NULL,
  `trusteeId2` varchar(255) DEFAULT NULL,
  `trusteeStatus2` varchar(255) DEFAULT NULL,
  `trusteePhone2` varchar(255) DEFAULT NULL,
  `trusteeSurname3` varchar(255) DEFAULT NULL,
  `trusteeName3` varchar(255) DEFAULT NULL,
  `trusteeId3` varchar(255) DEFAULT NULL,
  `trusteeStatus3` varchar(255) DEFAULT NULL,
  `trusteePhone3` varchar(255) DEFAULT NULL,
  `trusteeSurname4` varchar(255) DEFAULT NULL,
  `trusteeName4` varchar(255) DEFAULT NULL,
  `trusteeId4` varchar(255) DEFAULT NULL,
  `trusteeStatus4` varchar(255) DEFAULT NULL,
  `trusteePhone4` varchar(255) DEFAULT NULL,
  `beneficialSurname1` varchar(255) DEFAULT NULL,
  `beneficialName1` varchar(255) DEFAULT NULL,
  `beneficialStatus1` varchar(255) DEFAULT NULL,
  `beneficialOwnership1` varchar(255) DEFAULT NULL,
  `beneficialDob1` varchar(255) DEFAULT NULL,
  `beneficialAddress1` varchar(255) DEFAULT NULL,
  `beneficialPob1` varchar(255) DEFAULT NULL,
  `beneficialCountry1` varchar(255) DEFAULT NULL,
  `beneficialResidence1` varchar(255) DEFAULT NULL,
  `beneficialId1` varchar(255) DEFAULT NULL,
  `beneficialPhone1` varchar(255) DEFAULT NULL,
  `beneficialSurname2` varchar(255) DEFAULT NULL,
  `beneficialName2` varchar(255) DEFAULT NULL,
  `beneficialStatus2` varchar(255) DEFAULT NULL,
  `beneficialOwnership2` varchar(255) DEFAULT NULL,
  `beneficialDob2` varchar(255) DEFAULT NULL,
  `beneficialAddress2` varchar(255) DEFAULT NULL,
  `beneficialPob2` varchar(255) DEFAULT NULL,
  `beneficialCountry2` varchar(255) DEFAULT NULL,
  `beneficialResidence2` varchar(255) DEFAULT NULL,
  `beneficialId2` varchar(255) DEFAULT NULL,
  `beneficialPhone2` varchar(255) DEFAULT NULL,
  `beneficialSurname3` varchar(255) DEFAULT NULL,
  `beneficialName3` varchar(255) DEFAULT NULL,
  `beneficialStatus3` varchar(255) DEFAULT NULL,
  `beneficialOwnership3` varchar(255) DEFAULT NULL,
  `beneficialDob3` varchar(255) DEFAULT NULL,
  `beneficialAddress3` varchar(255) DEFAULT NULL,
  `beneficialPob3` varchar(255) DEFAULT NULL,
  `beneficialCountry3` varchar(255) DEFAULT NULL,
  `beneficialResidence3` varchar(255) DEFAULT NULL,
  `beneficialId3` varchar(255) DEFAULT NULL,
  `beneficialPhone3` varchar(255) DEFAULT NULL,
  `modeOfStatementDelivery` varchar(255) DEFAULT NULL,
  `statementFrequency` varchar(255) DEFAULT NULL,
  `sourceOfFunds` varchar(255) DEFAULT NULL,
  `initialInvestmentAmount` varchar(255) DEFAULT NULL,
  `topUps` varchar(255) DEFAULT NULL,
  `withdrawals` varchar(255) DEFAULT NULL,
  `anticipatedInvestmentAmount` varchar(255) DEFAULT NULL,
  `regularWithdrawal` varchar(255) DEFAULT NULL,
  `accountHolderInformation` varchar(255) DEFAULT NULL,
  `nameOfSignatory1` varchar(255) DEFAULT NULL,
  `nameOfSignatory2` varchar(255) DEFAULT NULL,
  `nameOfSignatory3` varchar(255) DEFAULT NULL,
  `relationshipManager` varchar(255) DEFAULT NULL,
  `processedBy` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `reviewedApprove` varchar(255) DEFAULT NULL,
  `executiveName` varchar(255) DEFAULT NULL,
  `comments` varchar(255) DEFAULT NULL,
  `clientVerificationScreening` varchar(255) DEFAULT NULL,
  `levelOfRisk` varchar(255) DEFAULT NULL,
  `appropriateDisclosure` varchar(255) DEFAULT NULL,
  `headOfState` varchar(255) DEFAULT NULL,
  `treasuryBill` varchar(255) DEFAULT NULL,
  `monthlyTurnover` varchar(255) DEFAULT NULL,
  `annualTurnover` varchar(255) DEFAULT NULL,
  `sig3ResidentialStatus` varchar(255) DEFAULT NULL,
  `sig3Gender` varchar(255) DEFAULT NULL,
  `sig2ResidentialStatus` varchar(255) DEFAULT NULL,
  `sig2Gender` varchar(255) DEFAULT NULL,
  `sig1ResidentialStatus` varchar(255) DEFAULT NULL,
  `riskTolerance` varchar(255) DEFAULT NULL,
  `investmentKnowledge` varchar(255) DEFAULT NULL,
  `investmentHorizon` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of corporate
-- ----------------------------
